package com.github.nanachi357.exchanges.bybit.model.response.order

import java.math.BigDecimal

data class BybitOrder(
    val orderId: String,
    val orderLinkId: String? = null,
    val blockTradeId: String? = null,
    val symbol: String,
    val price: BigDecimal? = null,
    val qty: BigDecimal,
    val side: String,
    val isLeverage: String? = null,
    val positionIdx: Int? = null,
    val orderStatus: String,
    val cancelType: String? = null,
    val rejectReason: String? = null,
    val avgPrice: BigDecimal? = null,
    val leavesQty: BigDecimal? = null,
    val leavesValue: BigDecimal? = null,
    val cumExecQty: BigDecimal? = null,
    val cumExecValue: BigDecimal? = null,
    val cumExecFee: BigDecimal? = null,
    val timeInForce: String? = null,
    val orderType: String,
    val stopOrderType: String? = null,
    val orderIv: String? = null,
    val triggerPrice: BigDecimal? = null,
    val takeProfit: BigDecimal? = null,
    val stopLoss: BigDecimal? = null,
    val tpTriggerBy: String? = null,
    val slTriggerBy: String? = null,
    val triggerDirection: Int? = null,
    val triggerBy: String? = null,
    val lastPriceOnCreated: String? = null,
    val reduceOnly: Boolean? = null,
    val closeOnTrigger: Boolean? = null,
    val smpType: String? = null,
    val smpGroup: Int? = null,
    val smpOrderId: String? = null,
    val tpslMode: String? = null,
    val tpLimitPrice: BigDecimal? = null,
    val slLimitPrice: BigDecimal? = null,
    val placeType: String? = null,
    val createdTime: Long? = null,
    val updatedTime: Long? = null
)
